k8s:
    deployments:
        d1:
            command:
                encoder:
                    name: jvm_opts
                    before:
                        - "java"
                        - "-server"
                    settings:
                        MaxHeapSize:
                            min: 1
                            max: 16
                            step: .25
                        GCTimeRatio:
                            min: 9
                            max: 99
                            step: 5
                    after:
                        - "-javaagent:/tmp/newrelic/newrelic.jar"
                        - "-Dnewrelic.environment=l1"
                        - "-jar"
                        - "/app.jar"
