k8s: {"whitelist_deployment_names":["nginx-deployment"], 
"control":{"userdata":{"deployment":"nginx-ref"}},
"application": {"components": {"nginx-deployment": {"settings": {"replicas": {"min": 3, "value": 3, "type": "range", "step": 1, "max": 3}}}}}}{
