# config without reference app
k8s: {"whitelist_deployment_names":["nginx-deployment"], 
"application": {"components": {"nginx-deployment": {"settings": {"replicas": {"min": 1, "value": 3, "type": "range", "step": 1, "max": 3}}}}}}
