name: Run Bento and Pytests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Bento
      run: |
        pip install bento-cli
        bento --agree --email=test@test.com init
        bento --agree --email=test@test.com check --all 2>&1

    - name: Setup test folder
      working-directory: ./tst
      run: |
        curl --remote-name https://raw.githubusercontent.com/opsani/servo/master/adjust.py
        mkdir encoders

    - name: Setup test encoders folder
      working-directory: ./tst/encoders
      run: |
        curl --remote-name-all \
        https://raw.githubusercontent.com/opsani/servo/master/encoders/base.py \
        https://https://raw.githubusercontent.com/opsani/encoder-jvm/master/encoders/jvm.py

    - name: Start Minikube Cluster
      run: minikube start

    - name: Test with pytest
      working-directory: ./tst
      run: |
        pip install pytest requests-mock
        pytest
